DISPLAY_MOD_DIR := $(USERMOD_DIR)


SRC_USERMOD += $(DISPLAY_MOD_DIR)/display.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/hal_stm_lvgl/tft/tft2.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/hal_stm_lvgl/touchpad/touchpad.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/STM32F769I-Discovery/stm32f769i_discovery.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/STM32F769I-Discovery/stm32f769i_discovery_lcd.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/STM32F769I-Discovery/stm32f769i_discovery_sdram.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/STM32F769I-Discovery/stm32f769i_discovery_ts.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/HAL_Driver/Src/stm32f7xx_hal_dsi.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/Components/otm8009a/otm8009a.c
SRC_USERMOD += $(DISPLAY_MOD_DIR)/Utilities/Components/ft6x06/ft6x06.c



CFLAGS_USERMOD += $(CFLAGS)
CFLAGS_USERMOD += -DSTM32
CFLAGS_USERMOD += -DSTM32F7
CFLAGS_USERMOD += -DSTM32F769xx
CFLAGS_USERMOD += -DSTM32F769I_DISCO
CFLAGS_USERMOD += -DSTM32F769NIHx
#CFLAGS_USERMOD += -DUSE_HAL_DRIVER
CFLAGS_USERMOD += -DHAL_DSI_MODULE_ENABLED


CFLAGS_USERMOD += -I$(DISPLAY_MOD_DIR)
CFLAGS_USERMOD += -I$(DISPLAY_MOD_DIR)/hal_stm_lvgl
CFLAGS_USERMOD += -I$(DISPLAY_MOD_DIR)/Utilities/STM32F769I-Discovery

#SRC_USERMOD += $(DISPLAY_MOD_DIR)/BSP_DISCO_F469NI/Utilities/Fonts/font12.c
#CFLAGS_USERMOD += -I$(DISPLAY_MOD_DIR)/BSP_DISCO_F469NI

